# Generated by Django 3.1.2 on 2023-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_chambre', models.CharField(choices=[('standard', 'standard'), ('luxe', 'luxe'), ('familial', 'familial')], max_length=20)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
