# Generated by Django 3.1.2 on 2023-04-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230330_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chambre',
        ),
    ]
